// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjxbFvrLNR3JFyokBIMaBK5OLWx_pkPXo',
    appId: '1:790493812622:web:587a51e12078665a9036df',
    messagingSenderId: '790493812622',
    projectId: 'auth-65e41',
    authDomain: 'auth-65e41.firebaseapp.com',
    storageBucket: 'auth-65e41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALy4SiO6es-mPzkAcJIG2iehWcPJE_3Ts',
    appId: '1:790493812622:android:c321f6f6b8b4fdfb9036df',
    messagingSenderId: '790493812622',
    projectId: 'auth-65e41',
    storageBucket: 'auth-65e41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVIbqJuKFxp5aQd8vjCG8vebDfOCUxhqE',
    appId: '1:790493812622:ios:fdd0e95c911f3f979036df',
    messagingSenderId: '790493812622',
    projectId: 'auth-65e41',
    storageBucket: 'auth-65e41.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVIbqJuKFxp5aQd8vjCG8vebDfOCUxhqE',
    appId: '1:790493812622:ios:fdd0e95c911f3f979036df',
    messagingSenderId: '790493812622',
    projectId: 'auth-65e41',
    storageBucket: 'auth-65e41.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjxbFvrLNR3JFyokBIMaBK5OLWx_pkPXo',
    appId: '1:790493812622:web:4cb84a84f75b943b9036df',
    messagingSenderId: '790493812622',
    projectId: 'auth-65e41',
    authDomain: 'auth-65e41.firebaseapp.com',
    storageBucket: 'auth-65e41.appspot.com',
  );

}